name: example
on: [push, pull_request]
jobs:
  build-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i
      - run: npm run build-example
  
